# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-30 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofiledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledata',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
